services:
  - type: web
    name: abv_free_bot
    env: python
    pythonVersion: 3.11
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
